### ISSUE TITLE
Paper Title

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#14]
Ich füge hier schonmal einen Platzhalter für die Diskussion über den Paper Titel ein. Im Moment lautet der Arbeitstitel:

_"BigGIS: A Predictive and Prescriptive Geographic Information System based on **High-Dimensional Geo-Temporal Data Structures**"_

Gerade der kursiv und fett markierte letzte Teil kommt meiner Ansicht nach nicht so sehr zur Geltung im Paper und sollte durch eine treffendere Formulierung ersetzt werden.

Was meint ihr dazu?
@JulianBruns @frank-fzi @vsimko @seebacherd @SteinManuel @seebacherd

**Comment by IdealOutage** [comment]
Just an idea: _BigGIS: Using Big Data in Geographic Information Systems for Descriptive, Predictive and Prescriptive Analysis?_

**Comment by JulianBruns** [comment]
Das von Seebacherd gefällt mir noch nicht ganz, fehlt Unsicherheit.
Vor allem sollten, falls möglich, irgendwie unsere Kernpunkte (Continous Refinement, Unsicherheit, Experten, etc) irgendwie im Titel anklingen ... 

Oder dreist vom AHM kopiert:

BigGIS – Prescriptive geographical information systems (GIS) based on big data analytics infrastructures

**Comment by wipatrick** [comment]
Bitte mal eure Meinung zu den Vorschlägen:
@JulianBruns @frank-fzi @vsimko @SteinManuel @seebacherd 

Hier mal eine vorläufig Liste mit Vorschlägen: 
1. BigGIS: A Next Generation Predictive and Prescriptive Geographic Information System
2. BigGIS: A Next Generation Prescriptive Geographic Information System
3. BigGIS: A Prescriptive Geographical Information System Based on Big Data Analytics Infrastructures
4. BigGIS: Using Big Data in Geographic Information Systems for Descriptive, Predictive and Prescriptive Analysis
5. BigGIS: Considering Heterogeneity and Uncertainty in Spatio-Temporal Big Data
6. BigGIS: Mastering Heterogeneity and Uncertainty in Spatio-Temporal Big Data
7. BigGIS: A Continuous Refinement Approach to Master Heterogeneity and Uncertainty in Spatio-Temporal Big Data

**Comment by vsimko** [comment]
+1 for 7 and 6

**Comment by JulianBruns** [comment]
+1 for 1, 3 and 7

**Comment by frank-fzi** [comment]
+1 für 6 
ist nicht so sperrig und man kann den Impact schnell erfassen. Die anderen Vorschläge sind zwar spezifischer, aber teilweise etwas schwer zu verstehen. Da muss man den Titel 3x lesen und weiß trotzdem nicht, was man sich darunter vorzustellen hat

**Comment by wipatrick** [comment]
+1 für 6 und 7,
+1 für 7 (Jens)

**Comment by SteinManuel** [comment]
+1 für 7 (Daniel S. und ich) 
+0,5 für 4

**Comment by wipatrick** [comment]
ok eindeutiger Sieger ist die Nr. 7 👍 

damit können wir diesen Punkt auch schließen.
