### ISSUE TITLE
Abgrenzung der Begriffe "User", "Expert (Knowledge)" und "Semantics"

### ISSUE THREAD

**Issue by frank-fzi** [biggis-project/sigspatial16-paper#16]
In Figur 1 verwenden wir die Begriffe "User", "Expert" und "Semantics" als unabhängige Entitäten, die zueinander in Beziehung stehen. Für den Text brauchen wir noch eine Abgrenzung der Begriffe. Zum Beispiel muss der Unterschied zwischen "User" und "Expert" klar sein. Wenn wir "Expert" durch "Expert Knowledge" ersetzen, geht das aus meiner Sicht wieder sehr in Richtung "Semantics", da wir mit der Semantik sowohl domänenspezifisches Expertenwissen als auch technische Schnittstellen (Linked APIs) beschreiben können. Eine Möglichkeit wäre daher, die Semantik in "Technical Semantics" und "Domain Expert Semantics" aufzuteilen. So wie ich die Architektur im Moment verstehe, sollen die R-Gates zur Laufzeit durch automatische Prozesse gesteuert werden, nicht durch manuelles Eingreifen von Experten. Die einzige manuelle Interaktion findet dann durch den User statt. Was meint ihr?

**Comment by wipatrick** [comment]
Hab diese Abgrenzung ebenfalls in der aktuellen Version #17 in Kapitel 3.1 angemerkt.

**Comment by wipatrick** [comment]
Sollte im Paper erkennbar sein.
