### ISSUE TITLE
Reihenfolge Autoren für Paper

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#30]
Ich warte zwar noch auf die Rückmeldung von den Konferenzorganisatoren bzgl. des Styles für die Autoren, allerdings ist im letzten PR #29 mein Vorschlag für die Autorenreihenfolge.

Diese basiert auf meinem persönlichen, subjektiven Empfinden:
1. Patrick @wipatrick
2. Manuel @SteinManuel 
3. Daniel @seebacherd 
4. Julian @JulianBruns 
5. Matthias @frank-fzi 
6. Viliam @vsimko 
7. Jens @JensNimis 

Kommentare sind erwünscht.

**Comment by vsimko** [comment]
I have no specific requirements in this regard

**Comment by JulianBruns** [comment]
Seems fine to me -> Montag 12:00 würde ich als Deadline setzen

**Comment by JensNimis** [comment]
Passt für mich - nur wird das mit zweimal Nummer 1 wohl schwierig ;-)

**Comment by wipatrick** [comment]
Jap passt. Morgen 12:00 ist Deadline.

**Comment by frank-fzi** [comment]
Passt, allerdings muss bei den Fußnoten aus der 2 vor FZI noch eine 3 gemacht werden. Denke, das schaffen wir auch ohne Pull-Request.

**Comment by wipatrick** [comment]
sehr gut aufgepasst @frank-fzi 👍

**Comment by frank-fzi** [comment]
Paper Submission wurde verlängert von June 21, 2016 auf June 28, 2016 (midnight PT), wir haben also noch ein paar Tage für Korrekturen, falls dies Nötig sein sollte. [http://sigspatial2016.sigspatial.org/cfp/](url) Danke @wipatrick für das gute Zeitmanagement!

**Comment by wipatrick** [comment]
Danke für die Info @frank-fzi . Ich warte ja noch auf die Rückmeldung bzgl. des Templating für die Autoren, evtl. müssen wir also wirklich nochmal ran.

**Comment by wipatrick** [comment]
wir können diesen Punkt schließen.
