### ISSUE TITLE
Feedback Stefan

### ISSUE THREAD

**Issue by frank-fzi** [biggis-project/sigspatial16-paper#36]
Wie versprochen hier noch das Feedback von Stefan:
[FeedbackStefan.pdf](https://github.com/biggis-project/sigspatial16-paper/files/330307/FeedbackStefan.pdf)

Hauptpunkt ist, dass der Impact nicht klar wird. Das sollte sowohl im Abstract als auch in der Introduction klargestellt und abschließend diskutiert werden. Hat jemand eine Idee dazu? Ich mach mich mal daran, einen pull request für die Typos und Minors zu erstellen.

**Comment by wipatrick** [comment]
@frank-fzi 
Die Submission Deadline fürs Abstract ist nun bereits vorbei, ergo am Abstract-Teil wird nix mehr gedreht. Full Paper Submission ist für Dienstag angesetzt. Schick bitte bis morgen, **Freitag den 24.06. 12:00** den PR, damit ich nochmal drüber schauen kann.

**Comment by frank-fzi** [comment]
Das sehe ich anders als @wipatrick . Die Deadline für das Abstract haben wir eingehalten, Haken dran. Die Deadline für das Paper ist genau genommen am Mittwoch, 29. Juni 2016 9:00 Uhr deutscher Zeit. Bis dahin haben wir noch die Gelegenheit, das komplette Paper zu überarbeiten, inklusive Abstract und Titel. Die Zeit können wir nutzen, oder wir können sie einfach verstreichen lassen. Natürlich können wir das Paper auch erstmal so lassen, wie es ist, das Feedback der Reviewer abwarten und falls es akzeptiert wird das Feedback von Stefan zusammen mit dem Feedback der Reviewer in der Camera-Ready Version berücksichtigen. Selbst dann können wir noch Titel, Abstract, Grafiken und den ganzen Rest vom Paper komplett überarbeiten. Fix ist es erst, wenn die Deadline für die Camera-Ready Version vorbei ist, das ist frühestens Ende August. Als Erstautor liegt die Entscheidung natürlich in erster Linie bei dir @wipatrick, ich zwinge hier niemanden etwas auf. Ich denke nur, dass jedes konstrukive Feedback ein Geschenk an die (Erst-)Autoren ist, das man nicht ignorieren sollte. Aussagen wie "da wird nix mehr gedreht" finde ich daher etwas unpassend.
