### ISSUE TITLE
Role of (existing) workflow systems

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#39]
- [Taverna](https://taverna.incubator.apache.org/)
- [VisTrails](https://www.vistrails.org/index.php/Main_Page)
- [VERCE](http://www.verce.eu/index.php)

I guess we should mention VisTrails in the "Related Work" section.

We should be aware that adding a new Reference means loosing space on our 4-page paper. Maybe a footnote providing the link to these systems is sufficient, what do you think?

How does our approach differ from e.g. VisTrails?

**Comment by wipatrick** [comment]
@vsimko @frank-fzi: could you please help out here about vistrails? My understanding is that BigGIS isn't to be considered a workflow management system. When we talk about 

> ... to automatically deploy data transformation workflows ... Smart web services dynamically compose workflows of data sources and data transformation services adopted to the requirements of different GISs based on the semantic metadata

 in Sections 3.1.1 & 3.2.1 this only refers to the integration step of semantically described data sources right? Maybe we should replace the term workflow with integration which might not have this strong meaning. What do you think?

Here is what VisTrails states on their main page: 

> VisTrails is an open-source scientific workflow and provenance management system that provides support for simulations, data exploration and visualization. Whereas workflows have been traditionally used to automate repetitive tasks, for applications that are exploratory in nature, such as simulations, data analysis and visualization, very little is repeated---change is the norm. As an engineer or scientist generates and evaluates hypotheses about data under study, a series of different, albeit related, workflows are created while a workflow is adjusted in an interactive process. VisTrails was designed to manage these rapidly-evolving workflows.
> 
> A key distinguishing feature of VisTrails is a comprehensive provenance infrastructure that maintains detailed history information about the steps followed and data derived in the course of an exploratory task: VisTrails maintains provenance of data products, of the workflows that derive these products and their executions. This information is persisted as XML files or in a relational database, and it allows users to navigate workflow versions in an intuitive way, to undo changes but not lose any results, to visually compare different workflows and their results, and to examine the actions that led to a result. It also enables a series operations and user interfaces that simplify workflow design and use, including the ability to create and refine workflows by analogy and to query workflows by example.

**Comment by wipatrick** [comment]
as a first suggestion:

Section 3.1.2:

> The former abstracts away the user from manually performing data integration steps to unify ...

Section 3.2.1:

> Smart web services dynamically integrate various data sources and automatically apply data transformation steps based on semantic metadata.

**Comment by vsimko** [comment]
Regarding the sentence "The former abstracts...", you probably meant "Section 3.1.2" ?
In both cases the new wording is OK.
BigGIS does not aim at composing workflows from heterogeneous services and making them reproducible. We aim at bigdata in GIS domain and provide a tool set to:
- integrate data sources
- treat uncertainty as a crucial part of every piece of data 
- analyze the data interactively
- keep some pipelines running in a stream-based fashion and continuously collect/visualize the results

**Comment by wipatrick** [comment]
see PR #49
