### ISSUE TITLE
Review initial proposal

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#4]
Please review initial proposol for our vision paper, mainly the high-level workflow described by the image.

**Comment by wipatrick** [comment]
## **Key questions:**
- [x] What is the novelty of BigGIS? What is our contribution?
- [ ] How does a high-level workflow look like? Without going to much into architectural details at first.
- [ ] How can the human be part of this pipeline/platform? Interaction etc.?
- [ ] How can BigGIS help to bridge the usability gab between raw data from various types of data sources and feature extraction/information gain/insight?
- [ ] How to handle uncertainty in data?

**Main parts:** 
- [ ] Integrated analytical pipeline approach
- [ ] Modelling uncertainty
- [ ] Feedback/Enhancement through expert knowledge
- [ ] Leveraging semantics
- [ ] Handling Big Data related characteristics (volume, velocity, variety, veracity, value)

## **Key ideas:**
- [ ] Concept of Continuous Refinement Process (on the basis of [continuous improvement process](https://en.wikipedia.org/wiki/Continual_improvement_process)
- [ ] The basic assumption would be that uncertainty in data is inversely related to gaining valuable insight, i.e. by minimizing the uncertainty in data throughout the analytical pipeline the user can expect a higher information gain.
- [ ] Minimizing the uncertainty is done in a twofold approach: (1) Modelled on analytical level within the modules of the pipeline (2) Through defined access points called Refinement Gates (or R-Gates) on Expert and Semantics Level. The Semantics Layer is thereby supporting the experts knowledge extraction process e.g. by linking useful information through semantic annotation of data sources (Linked APIs). 
- [ ] Thereby on system level, the automated processing gets enhanced by a hybridly-optimized (through human and machine/semantics) ML approach and therefore continuously refining the quality of the results.

## **Key considerations:**

**Technical aspects:**
- [ ] Architectural, integrated pipeline consisting of several components
- [ ] Components are functional units which are responsible for fulfilling certain functional requirements
- [ ] A component can consist of various modules which in depths are responsible for fulfilling various tasks according to their functional requirement
- [ ] Modules are classified as as core + on-demand

**User aspects:**
- [ ] Interaction is based on the Knowledge Generation Model for Visual Analytics
- [ ] User interacts with the system via scenario dependent visual interface
- [ ] He receives data in a adequate visual format so he can easily interpret the presented information
- [ ] If needed he can manipulate the shown visualization such that he can explore the data in a self-service manner
- [ ] User receives direct support from two sides: (1) Human-level (2) Machine-level
- [ ] Human-level: Expert knowledge support (domain and technology knowledge)
- [ ] Machine-level: Semantics reasoning support (Cognitive Apps, Linked APIs)

**Comment by JulianBruns** [comment]
Would go away from pure pipeline as a concept and instead of reinforcing circle.
Or "Analytical Clusterfuck" as working visualization

**Comment by wipatrick** [comment]
I'd stick with the integrated (reinforced) pipeline as a visual concept because (1) its more easily interpretable (2) it reflects the master "stream" where data is processed as in a special version of the pipes-and-filters architectural pattern, where feed back loops are allowed. "Integrated" can in general also mean, integrating e.g. human-expert knowledge

see:
https://de.wikipedia.org/wiki/Pipes_und_Filter

**Comment by SteinManuel** [comment]
Hallo zusammen (Ich schreibe das Ganze hier mal in Deutsch, da wir generell eigentlich alle Deutsch verstehen und ich denke, dass die Diskussion so nochmal flüssiger wird :-) ). 

Daniel und ich sind jetzt einmal umfassend durch das Paper gegangen und haben den Input von unserer Seite aus in roter Farbe eingetragen. Am Besten einfach mal das Paper compilieren und anschauen. 

Für die Analytical Pipeline in Figure 1 wünschen wir uns noch eine Step-by-Step Beschreibung im Paper (Muss ja sowieso gemacht werden :-) ). Dann können wir auch besser darüber diskutieren, was noch fehlt oder vielleicht missverständlich rüberkommt (am besten via Skype, sobald die Beschreibung im Paper steht). Momentan gefällt uns die Pipeline schon gut (stilistisch gesehen kann aber natürlich noch das ein oder andere getan werden, um es noch professioneller wirken zu lassen). Die zwei Balken unten (Veracity und Value) finden wir ist eine sehr nette Metapher um zu zeigen, wie die Unsicherheit am Anfang groß und mit der Zeit durch das Wissen (sozusagen) abnimmt. Auch ist die generelle Richtung von Links nach Rechts unserer Meinung nach sehr gut. Ich glaube wir sind da schon auf einem guten Weg. 

Ansonsten würde ich sagen ist es jetzt an der Zeit, dass der Erstautor einen ersten Fließtext-Draft der Introduction schreibt, so wie er ihn sich vorstellt, damit wir danach wieder sehen können, ob die Geschichte bereits konsistent ist.

**Comment by wipatrick** [comment]
@SteinManuel @seebacherd Danke für eure Anmerkungen 👍 

Ich werde die kommenden Tage einen ersten Entwurf der Introduction als Fließtext aufsetzen. 

BTW: Ihr wisst ja wer sich da gerade für die Überarbeitung der Grafik(en) qualifiziert hat? ^^

**Comment by SteinManuel** [comment]
Oh. OH. Oh Nein.

**Comment by vsimko** [comment]
If possible, please use some open format for the images.
As I mentioned in [figures/README.md](https://github.com/biggis-project/sigspatial16-paper/blob/master/figures/README.md), we can then automatically convert figures into PDF using [figconv](https://github.com/vsimko/figconv).
