### ISSUE TITLE
General statement to identified challenges

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#44]
General: Why these challenges at all?
- Relevant Section: 3.2

**Comment by JulianBruns** [comment]
Difficult ...  Related work will be annoying,
3.2.1 Perhapbs here related work? more architecture problem/begründung?
3.2.2 Dimension reduction is based on (near) real time constraints -> and perhaps shortcoming of other disaster management?
3.2.3.  I think our reasoning here is enough

**Comment by wipatrick** [comment]
I also would not write more related work - not for this topic. we just add some references to section 3 or fig. 1 to make it more clear.

**Comment by wipatrick** [comment]
See PR #49
