### ISSUE TITLE
Rephrasing "Fast Computation"

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#47]
Rephrasing the word "fast computation" (what does it mean?)
- Relevant Section: 3.2.2

**Comment by wipatrick** [comment]
maybe rephrasing to "fast processing" or "(near) real-time processing" or "ultra-supersonic-speedy computation" :)

**Comment by JulianBruns** [comment]
Computation enables (near) real-time use is meant with fast computing

**Comment by wipatrick** [comment]
see PR #49
