### ISSUE TITLE
VA Terminologie in Vision Paper

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#5]
Hi @seebacherd  @SteinManuel 

ich habe nun mal intensiv das "Knowledge Generation Model for VA" Paper durchgearbeitet und bin nun an einer Stelle etwas unschlüssig was die genau Terminologie angeht in unserem Vision Paper.

Und zwar hatte ich bei dem größer werdenden Balken unten bei der Abbildung **Value (Insight)** stehen. Und ich überlege gerade, ob da nicht besser **Value (Knowledge)** stehen sollte.

Streng genommen ist ja Insight nicht gleich Knowledge. Entweder ist 
(a) das "Indiz" (engl. evidence) so stark, dass der User sofort davon überzeugt ist und aus dem Insight Knowledge wird.
(b) das "Indiz" schwach, was zum Insight führt, den User allerdings in der Verification Loop kreisen lässt bis er irgendwann genug Indizien gesammelt hat und er seine Hypothese verifiziert/falsifiziert und er so Knowledge generiert.

Also Sollte dort als Ziel in Anlehnung an VA wohl besser die Maximierung des Knowledges und nicht nur des Insights stehen.

Was meint ihr?

ps: sry für dieses denglisch :)

**Comment by SteinManuel** [comment]
Hi Patrick, 

entschuldie die kleine Verzögerung. Ich stimme dir zu, dass wir besser "knowledge" nehmen sollten. Knowledge ist ein stärkeres Wort (wie schön von dir ausgeführt) und führt zu unserem finalen Ziel, dem Gewinn von Wissen. Insight ist hingegen eigentlich ja "nur" der Weg zum Wissen, also sind wir mit "Insight" allein lediglich auf dem Weg, aber noch nicht am Ziel. 

Gerade hab ich mich noch gefragt, ob man die Feedback Loop auch unten bei den zwei größer bzw. kleiner werdenden Balken andeuten kann, oder ob unsere momentane Repräsentation schon ausreicht. 

Viele Grüße!

**Comment by wipatrick** [comment]
Danke für dein Feedback. Da sind wir ja d'accord. 

Solch eine Idee hatte ich auch schon. In meinem Notizbuch habe ich auch mal Versuche unternommen es visuell darzustellen. Allerdings bin ich noch nicht zufrieden :)

**Comment by wipatrick** [comment]
Änderungen sind eingepflegt in Abbildung. Daher schließe ich diesen Punkt.
