### ISSUE TITLE
Umgang mit Uncertainty

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#6]
@JulianBruns @SteinManuel @seebacherd @frank-fzi 

Bitte beschreibt hier mal aus der Sicht von Analytics, Visual Analytics und Semantics wie mit Unsicherheit umgegangen wird.

Hintergrund: In der Introduction, die ich später uploaden werde, sage ich, dass die Big Data induzierten Anforderungen Volume + Velocity gut abgedeckt sind. Durch BigGIS decken wir allerdings noch Variety und Veracity (Uncertainty) ab.

**Analytics:**
Wie kann Analytics beim Thema Uncertainty unterstützen? Gibt es bestimmte robustere Algorithmen für gewisse Aufgaben?

**Semantics:** 
So wie ich es sehe, hilft Semantics bei Variety durch (1) Datentransformation und (2) Möglichkeit automatisiert, ausrollbare Workflows zu definieren. Wie genau hilft Semantics bei Uncertainty?

**Visual Analytics:**
Für VA habe ich das folgende Paper gelesen von eueren Kollegen gelesen [The Role of Uncertainty, Awareness and Trust in Visual Analytics ](https://bib.dbvis.de/uploadedFiles/3_preprint.pdf). Diese Erkenntnisse sollten wir auf alle Fälle mit einfließen lassen. Auch mit Blick auf unser Continuous Refinement Model.

**Comment by frank-fzi** [comment]
Aus meiner Sicht kann die Semantic gut dazu verwendet werden, die Provenance der Daten zu beschreiben, woraus sich dann mit entsprechenden Regeln Uncertainty ableiten lässt. Ggf. könnten hier auch Machine Learning Verfahren zum Einsatz kommen, um diese Bewertung zur Laufzeit durch Nutzerevaluierung zu verbessern. Mehr als Anschneiden können wir das Thema im Vision Paper aber vermutlich noch nicht.

**Comment by wipatrick** [comment]
Gut sowas reicht ja aber vollkommen aus, aus meiner Sicht. So können wir argumentativ das Ganze mit relevantem (wenngleich minimalem) Inhalt füllen

**Comment by IdealOutage** [comment]
In 51455ecd8c339682f50470896a14d2eedc066ded habe ich noch eine zusätzliche Quelle zum Umgang mit _Uncertainty_ und _Large Scale Geo-Spatial Data_ hinzugefügt.

**Comment by wipatrick** [comment]
Thx. Werde ich mir mal noch anschauen.

**Comment by JulianBruns** [comment]
Werde da bei Analytics vor allem über Bayes-Verfahren argumentieren. Dort wird die Unsicherheit explizit modelliert und die Vorhersagen/Ergebnisse spiegeln auch das Maß an Sicherheit/Vertrauen in den Forecast wieder

**Comment by wipatrick** [comment]
Julian hat hier #21 einen schönen Teil "3.1.4 Modelling Uncertainty" geschrieben, der die Ausführungen von Matthias aus Sicht der Semantik schön umschließt. Sollte aus VA Sicht noch etwas ergänzend hinzugefügt werden? @seebacherd @SteinManuel 

Ansonsten könnten wir den Punkt schließen

**Comment by JulianBruns** [comment]
Vorschlag: Punkt schliessen?

**Comment by wipatrick** [comment]
Passt 👍
