### ISSUE TITLE
Erster Entwurf der Paper Struktur und Introduction

### ISSUE THREAD

**Issue by wipatrick** [biggis-project/sigspatial16-paper#8]
@JulianBruns @frank-fzi @bamfz @SteinManuel @seebacherd @vsimko

Der erste Entwurf der Paper Struktur steht. Daneben habe ich auch nach bestem Wissen und Gewissen eine vorläufige Introduction verfasst.

Nun meine Aufforderung an alle bis **spätestens Mittwoch, 18.05.2016**: 
1. lest mal drüber. Ich bin offen für jeglichen Anregungen
2. überall wo **ToDO@all** steht, seid ihr alle gemeint. Macht euch in diesem Kontext bitte ebenfalls Gedanken über möglichen Inhalt.
3. überall wo **ToDO@Name** steht, was sich im Moment noch auf den Related Work und Influences Bereich beschränkt, sollten relevante Textbausteine aus den jeweiligen Forschungsbereichen kommen, welche BigGIS bzw. die Vision von BigGIS prägen. Bitte denkt daran, wir haben in Summe 4 Seiten.

Ich werde nun parallel dazu einen ersten Entwurf des Continuous Refinement Model Workflows in Abschnitt 3 verfassen.

Ich weiß, dass bis dahin nicht mehr viel Zeit ist. Allerdings kommen nun 2x Feiertage mit kurzen Wochen, dann ist das All-Hands Meeting Anfang Juni und schon ist Paper Deadline am 14.06.2016. Zudem ist es ja auch nicht verkehr mal früher als auf den letzten Drücker fertig zu sein :)

**Comment by frank-fzi** [comment]
Hi Patrick,

super, vielen Dank für deine Mühen! Gestern hab ich noch ein zweites Paper zu Smart Web Services in der Camera-Ready version fertig gemacht, jetzt haben wir zwei Referenzen in dem Bereich. Werde mich heute Nachmittag direkt mal dran machen, das ins Vision Paper zu bringen.

Kann es sein, dass beim Mergen etwas schief gelaufen ist? Es gibt jetzt zweit Titel mit keim2010mastering in biggis-paper.bib, erst wenn eins von beidem umbenannt wird kann der code compiliert werden. Kannst du das nachvollziehen?

Gruß
Matthias

**Comment by wipatrick** [comment]
@frank-fzi bitte nochmal probieren. Der doppelte Eintrag sollte nun weg sein.

**Comment by frank-fzi** [comment]
läuft

**Comment by IdealOutage** [comment]
See PR: #15
